[server]
host = "0.0.0.0"
port = 8000

[client]
dns_threads = 4

[[nodes]]
bitcoin_rpc_urls = "http://localhost:18332"
bitcoin_rpc_user = "xyz"
bitcoin_rpc_password = "xyz"

[[nodes]]
bitcoin_rpc_urls = "http://localhost:18332"
bitcoin_rpc_user = "xyz"
bitcoin_rpc_password = "xyz"

[cpu_pool]
size = 1

[opsgenie]
enabled = true
api-key = "b9a4dd35-cbad-4324-ab76-0583ae538960"
url = "https://api.opsgenie.com/v2/alerts"
team = "ops_team"

[healthcheck]
timeout = 60 # in seconds - 1 min
url = "https://blockchain.info/q/getblockcount"
quarantine = 600 # in seconds - 10 min
